# The usage of random.seed()

如果使用了 random.seed()，那么每次所产生的随机数将与前面一次的相同。

In [13]:
import numpy as np

np.random.seed(20)

runningtimes=0
while (runningtimes <=10):
    x = np.random.randn(5)
    print(x)
    print('**')
    runningtimes=runningtimes+1

[ 0.88389311  0.19586502  0.35753652 -2.34326191 -1.08483259]
**
[ 0.55969629  0.93946935 -0.97848104  0.50309684  0.40641447]
**
[ 0.32346101 -0.49341088 -0.79201679 -0.84236793 -1.27950266]
**
[ 0.24571517 -0.0441948   1.56763255  1.05110868  0.40636843]
**
[-0.1686461  -3.18970279  1.12013226  1.33277821 -0.24333877]
**
[-0.13003071 -0.10901737  1.55618644  0.12877835 -2.06694872]
**
[-0.88549315 -1.10457948  0.93286635  2.059838   -0.93493796]
**
[-1.61299022  0.52706972 -1.55110074  0.32961334 -1.13652654]
**
[-0.3384906   0.32097078 -0.60230802  1.54472836  0.64703408]
**
[0.59321721 0.4380245  1.35778902 1.20451128 1.35179619]
**
[ 4.93437236e-01 -2.70436525e+00 -5.55185797e-01  1.50856026e-03
  8.57093817e-01]
**


In [11]:
import numpy as np


runningtimes=0
while (runningtimes <=10):
    np.random.seed(5)
    x = np.random.randn(5)
    print(x)
    print('**')
    runningtimes=runningtimes+1

[ 0.44122749 -0.33087015  2.43077119 -0.25209213  0.10960984]
**
[ 0.44122749 -0.33087015  2.43077119 -0.25209213  0.10960984]
**
[ 0.44122749 -0.33087015  2.43077119 -0.25209213  0.10960984]
**
[ 0.44122749 -0.33087015  2.43077119 -0.25209213  0.10960984]
**
[ 0.44122749 -0.33087015  2.43077119 -0.25209213  0.10960984]
**
[ 0.44122749 -0.33087015  2.43077119 -0.25209213  0.10960984]
**
[ 0.44122749 -0.33087015  2.43077119 -0.25209213  0.10960984]
**
[ 0.44122749 -0.33087015  2.43077119 -0.25209213  0.10960984]
**
[ 0.44122749 -0.33087015  2.43077119 -0.25209213  0.10960984]
**
[ 0.44122749 -0.33087015  2.43077119 -0.25209213  0.10960984]
**
[ 0.44122749 -0.33087015  2.43077119 -0.25209213  0.10960984]
**


# Under stand how path is joined

Here, I use a simple example to show how we generate a path in python.

In [15]:
import os
PROJECT_ROOT_DIR = '.'
CHAPTER_ID = '001'
fig_id = '300'
path = os.path.join(PROJECT_ROOT_DIR, "images", CHAPTER_ID, fig_id + ".png")
print(path)

./images/001/300.png
