In [1]:
4.124033380*2

8.24806676

In [2]:
9.667174099/8.24806676

1.1720533284092864

In [22]:
1.1720533284092864*2

2.344106656818573

In [3]:
numpy.cos(42.849)

NameError: name 'numpy' is not defined

In [4]:
import numpy as np

In [21]:
np.cos(62.206*np.pi/180)

0.46629400467970167

In [13]:
np.pi

3.141592653589793

In [15]:
np.cos(45*np.pi/180)

0.70710678118654757

In [23]:
1.8423814999999997/(1.8423814999999997*2)

0.5

In [26]:
#YC2
celldm1=1.8423814999999997*2
celldm1

3.6847629999999993

In [27]:
3.1056759999999999/(1.8423814999999997*2)

0.8428428097003797

In [28]:
import numpy as np

In [29]:
lattice_POSCAR=np.array([[-1.8423814999999997,    1.8423814999999997,    3.1056759999999999,],
                        [1.8423814999999997,   -1.8423814999999997,    3.1056759999999999],
                        [1.8423814999999997,    1.8423814999999997,   -3.1056759999999999]])

In [31]:
print('lattice_POSCAR unit is angstrom')

lattice_POSCAR unit is angstrom


In [38]:
print('convert angstrom to bohr: 1 angstrom = 1.88973 Bohr')
ang2bohr=1.88973

convert angstrom to bohr: 1 angstrom = 1.88973 Bohr


In [40]:
lattice_POSCAR_bohr = lattice_POSCAR*ang2bohr
print(lattice_POSCAR_bohr)
#YC2 3.6813 6.1886

[[-3.48160359  3.48160359  5.86888911]
 [ 3.48160359 -3.48160359  5.86888911]
 [ 3.48160359  3.48160359 -5.86888911]]


In [49]:
celldm1=np.abs(lattice_POSCAR_bohr[0][0]*2)
print('celldm1 is ', celldm1, 'bohr')

celldm1 is  6.96320718399 bohr


In [47]:
CELL_PARAMETERS=lattice_POSCAR_bohr/celldm1
CELL_PARAMETERS

array([[-0.5       ,  0.5       ,  0.84284281],
       [ 0.5       , -0.5       ,  0.84284281],
       [ 0.5       ,  0.5       , -0.84284281]])

In [50]:
#the c/a used for kpoints.x
ca_ratio_kpoints = np.abs(CELL_PARAMETERS[0][2])*2
ca_ratio_kpoints

1.6856856194007597

In [1]:
0.771353467*2

1.542706934

In [1]:
#1 Ry = 13.605698065894 eV
5.280616/13.605698065894

0.3881179763379545

In [ ]:
# YC2 paper 

The electroic specific head coefficient gamma is calculated from 

$\gamma$ = $\frac{1}{3} \pi^2 k_B^2 N(E_F)(1+\lambda)$

Using the data of Table III of paper "A comparative ab initio study of superconductivity in the body centered
tetragonal YC2 and LaC2"

In [14]:
import numpy as np

kb= 1.38064852E-23 #m2 kg s-2 K-1
# kb also equas to 1.38064852E-23 J/K
kb_mj = 1.38064852E-20 #mj/K

#R=8.3145 # J/(mol*k)

In [9]:
pi=np.pi
pi

3.141592653589793

In [11]:
N_EF=0.78 # states/eV
ep_lambda=0.56

In [18]:
gamma = pi*pi*kb*kb*N_EF*(1+ep_lambda)/3
gamma


7.63069254027711e-46

 因为分子中有 mj的二次方，正好N_EF的单位是 states/eV，因此可以将分子中的一个mj跟eV进行化简。
 


In [23]:
gamma = pi*pi*kb_mj*kb_mj*N_EF*(1+ep_lambda)/3 
# the unit of gamma is(mj/k)^2 * states/eV
gamma

7.630692540277111e-40

In [26]:
gamma_brief=gamma*6.02E23*6.242E15
gamma_brief # unit of gamma_brief is mj/(k^2 mol) 
# 2.86

2.8673731267518656

In [ ]:
# 1 mj = 6.242E15
# 1 mol = 6.02E23

# New lambda calculations

## 1. Rexlations

### 1.1 P = 0 GPa

#### 1.1.1 Before relaxing with high accuracy

In [4]:
#For P = 0 GPa
#the initial crystal structure is relaxed by 40 Ry
import numpy as np
lattice_POSCAR_bohr=np.array([
    [-4.167619347,   4.167619347,   9.767254194],
    [4.167619347,  -4.167619347,   9.767254194],
    [4.167619347,   4.167619347,  -9.767254194]   
])
print(lattice_POSCAR_bohr)


[[-4.16761935  4.16761935  9.76725419]
 [ 4.16761935 -4.16761935  9.76725419]
 [ 4.16761935  4.16761935 -9.76725419]]


In [5]:
celldm1=np.abs(lattice_POSCAR_bohr[0][0]*2)
print('celldm1 is ', celldm1, 'bohr')

celldm1 is  8.335238694 bohr


In [6]:
CELL_PARAMETERS=lattice_POSCAR_bohr/celldm1
CELL_PARAMETERS

array([[-0.5       ,  0.5       ,  1.17180258],
       [ 0.5       , -0.5       ,  1.17180258],
       [ 0.5       ,  0.5       , -1.17180258]])

#### 1.1.2 After relaxing with high accuracy

In [17]:
#For P = 0 GPa
#the final crystal structure is relaxed by 50 Ry
#  etot_conv_thr=1.0D-8,
#  forc_conv_thr=1.0D-5,
#         CELL_PARAMETERS (alat=  8.33523869)
#           -0.510986509   0.510986509   1.193854227
#            0.510986509  -0.510986509   1.193854227
#            0.510986509   0.510986509  -1.193854227

#         ATOMIC_POSITIONS (crystal)
#         Ba       0.000000000   0.000000000   0.000000000
#         As       0.370841407   0.370841407  -0.000000000
#         As       0.629158593   0.629158593  -0.000000000
#         Pd       0.750000000   0.250000000   0.500000000
#         Pd       0.250000000   0.750000000   0.500000000
#         End final coordinates


import numpy as np
lattice_POSCAR_bohr=8.33523869*np.array([
    [-0.510986509,   0.510986509,   1.193854227],
    [0.510986509,  -0.510986509,   1.193854227],
    [0.510986509,   0.510986509,  -1.193854227]
])
print(lattice_POSCAR_bohr)

[[-4.25919452  4.25919452  9.95105994]
 [ 4.25919452 -4.25919452  9.95105994]
 [ 4.25919452  4.25919452 -9.95105994]]


In [18]:
celldm1=np.abs(lattice_POSCAR_bohr[0][0]*2)
print('celldm1 is ', celldm1, 'bohr')

celldm1 is  8.51838903977 bohr


In [19]:
CELL_PARAMETERS=lattice_POSCAR_bohr/celldm1
CELL_PARAMETERS

array([[-0.5       ,  0.5       ,  1.16818566],
       [ 0.5       , -0.5       ,  1.16818566],
       [ 0.5       ,  0.5       , -1.16818566]])

#### 1.1.2 After relaxing with high accuracy

### 1.2 P = 5 GPa
#### 1.2.1 Before relaxing with high accuracy

In [13]:
#For P = 5 GPa
#the initial crystal structure is relaxed by 40 Ry
import numpy as np
lattice_POSCAR_bohr=np.array([
    [-4.124033380,   4.124033380,   9.667174099],
    [4.124033380,  -4.124033380,   9.667174099],
    [4.124033380,   4.124033380,  -9.667174099]
 
])
print(lattice_POSCAR_bohr)


[[-4.12403338  4.12403338  9.6671741 ]
 [ 4.12403338 -4.12403338  9.6671741 ]
 [ 4.12403338  4.12403338 -9.6671741 ]]


In [10]:
celldm1=np.abs(lattice_POSCAR_bohr[0][0]*2)
print('celldm1 is ', celldm1, 'bohr')

celldm1 is  8.24806676 bohr


In [11]:
CELL_PARAMETERS=lattice_POSCAR_bohr/celldm1
CELL_PARAMETERS

array([[-0.5       ,  0.5       ,  1.17205333],
       [ 0.5       , -0.5       ,  1.17205333],
       [ 0.5       ,  0.5       , -1.17205333]])

#### 1.2.2 After relaxing with high accuracy

In [20]:
#For P = 5 GPa
#the final crystal structure is relaxed by 50 Ry
#  etot_conv_thr=1.0D-8,
#  forc_conv_thr=1.0D-5,
# CELL_PARAMETERS (alat=  8.24806676)
#   -0.507880635   0.507880635   1.181747340
#    0.507880635  -0.507880635   1.181747340
#    0.507880635   0.507880635  -1.181747340

# ATOMIC_POSITIONS (crystal)
# Ba      -0.000000000  -0.000000000  -0.000000000
# As       0.374161901   0.374161901  -0.000000000
# As       0.625838099   0.625838099   0.000000000
# Pd       0.750000000   0.250000000   0.500000000
# Pd       0.250000000   0.750000000   0.500000000
# End final coordinates


import numpy as np
lattice_POSCAR_bohr=8.24806676*np.array([
  [-0.507880635,   0.507880635,   1.181747340],
   [0.507880635,  -0.507880635,   1.181747340],
   [0.507880635,   0.507880635,  -1.181747340],
])
print(lattice_POSCAR_bohr)

[[-4.18903338  4.18903338  9.74713095]
 [ 4.18903338 -4.18903338  9.74713095]
 [ 4.18903338  4.18903338 -9.74713095]]


In [21]:
celldm1=np.abs(lattice_POSCAR_bohr[0][0]*2)
print('celldm1 is ', celldm1, 'bohr')

celldm1 is  8.37806676718 bohr


In [22]:
CELL_PARAMETERS=lattice_POSCAR_bohr/celldm1
CELL_PARAMETERS

array([[-0.5       ,  0.5       ,  1.16341051],
       [ 0.5       , -0.5       ,  1.16341051],
       [ 0.5       ,  0.5       , -1.16341051]])

### 1.3 P = 10 GPa

#### 1.3.1 Before  relaxing with high accuracy


In [14]:
#For P = 10 GPa
#the initial crystal structure is relaxed by 40 Ry
import numpy as np
lattice_POSCAR_bohr=np.array([
    [-4.083167434,   4.083167434,   9.578539714],
    [4.083167434,  -4.083167434,   9.578539714],
    [4.083167434,   4.083167434,  -9.578539714]
])
print(lattice_POSCAR_bohr)


[[-4.08316743  4.08316743  9.57853971]
 [ 4.08316743 -4.08316743  9.57853971]
 [ 4.08316743  4.08316743 -9.57853971]]


In [15]:
celldm1=np.abs(lattice_POSCAR_bohr[0][0]*2)
print('celldm1 is ', celldm1, 'bohr')

celldm1 is  8.166334868 bohr


In [16]:
CELL_PARAMETERS=lattice_POSCAR_bohr/celldm1
CELL_PARAMETERS

array([[-0.5       ,  0.5       ,  1.17293007],
       [ 0.5       , -0.5       ,  1.17293007],
       [ 0.5       ,  0.5       , -1.17293007]])