# 阅读笔记

** 作者：方跃文 **

** Email: fyuewen@gmail.com **

** 时间：始于2017年9月12日， 结束写作于 **

** 第四章笔记始于2017年10月17日，结束于_____**



# 第四章 Numpy基础：数组和矢量计算

** 时间： 2017年10月17日早晨**

Numpy，即 numerical python的简称，是高性能科学计算和数据分析的基础包。它是本书所介绍的几乎所有高级工具的构建基础。其部分功能如下：

1. ndarray，一个具有矢量算数运算和复杂广播能力的快速且节省空间的多维数组

2. 在不需要循环的情况下，用于对数组快速运算的标准数学函数

3. 用于读写磁盘数据的工具以及用于操作内存映射文件的工具

4. 线性代数、随机数生成以及傅里叶变化

5. 用于集成由 C、C++、Fortran 等语言编写的代码的工具

Numpy 本身功能不复杂，但是理解 Numpy 有助于更高效地使用诸如 Pandas 之类的工具。

原书作者主要从事数据分析，所以他关注的功能主要集中于：

1. 用于数据整理和清理、子集构造和过滤、转换等快速的矢量化数组运算

2. 常用的数组算法，如排序、唯一化、集合运算等。

3. 高效地描述统计和数据聚合/摘要运算

4. 用于异构数据集的合并/连接运算的数据和关系型数据运算

5. 将条件逻辑表述为数组表达式（而不是带有if-elif-else分支的循环）

6. 数据的分组运算（聚合、转换、函数应用等）第五章将对此进行详细解释。

注：建议总是使用 import numpy as np； 而不是用 from numpy import *

## Numpy 的 ndarray：一种多维数组对象

** 时间： 2017年10月18日晚**

Numpy 一个重要特点就是其 N 维数组对象，即 ndarray，该对象是一个快速而灵活的数据集容器。我们可以利用这种数组对整块数据进行一些运算，它的语法跟标量元素之间的运算相同：

In [12]:
import numpy.random as nrandom
data = nrandom.randn(3,2)

In [13]:
data

array([[-0.99800656,  0.16535264],
       [ 0.93812685, -0.58386599],
       [ 0.04130164,  1.67020695]])

In [14]:
data*10

array([[ -9.98006558,   1.65352642],
       [  9.38126851,  -5.83865987],
       [  0.41301638,  16.70206948]])

In [15]:
data + data

array([[-1.99601312,  0.33070528],
       [ 1.8762537 , -1.16773197],
       [ 0.08260328,  3.3404139 ]])

ndarray 是 **同构**数据多维容器，that is to say, 所有元素必须是同类型的。

每个数组都有一个 shape （一个表示各维度大小的元祖）和一个 dtype （一个用于说明数组数据类型的对象）：

In [16]:
data.shape

(3, 2)

In [18]:
data.dtype

dtype('float64')

虽然大多数数据分析工作不需要深入理解Numpy，但是精通面向数组的编程和思维方式是成为 Python 科学计算达人的一大步骤。