In [18]:
import numpy as np
from numpy import matrix

a=matrix([0,0,1]);
print(a)
b=matrix([1,0,0]);
print(b)
print(a*b.T)

a_copy = np.array([0,0,1])
np.linalg.norm(a_copy)

[[0 0 1]]
[[1 0 0]]
[[0]]


1.0

matrix([[1, 0, 0]])

matrix([[0]])

In [2]:
import math

def dotproduct(a,b):
	return sum([a[i]*b[i] for i in range(len(a))])
 
from math import acos
 
#Calculates the size of a vector
def veclength(a):
	return sum([a[i]**2 for i in range(len(a))])**.5
 
#Calculates the angle between two vector
def ange(a,b):
	dp=dotproduct(a,b)
	la=veclength(a)
	lb=veclength(b)
	costheta=dp/(la*lb)
	return acos(costheta)

#vector1 = [-8.31409,    3.56542,    8.87916]
#vector4 = [-7.27189,    5.01510,   -8.99671]
vector1_pro =  [ -0.980,   0.533 ,    0]
vector4_pro =  [-1.086 ,  0.243,   0]

#a_angle = ange(vector1,vector4)
#print(math.degrees(a_angle))
a_angle_pro=ange(vector1_pro, vector4_pro)
print(math.degrees(a_angle_pro))


15.928203343001407


In [46]:
import math
a=math.tan(math.pi/6)
print(a)
b=0.805/1.365
b

0.5773502691896257


0.5897435897435898